version: "3"
volumes:
  mongo-db:
services:
  nginx:
    depends_on: 
      - node-app
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    depends_on: 
        - mongo
    volumes:
        - ./:/app
        - /app/node_modules
    build: .
    image: zeezomozi/node-app
    environment: 
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    # ports:
    #   - "3000:3000"
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  redis:
    image: redis