version: "3"
volumes:
  mongo-db:
services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    depends_on: 
        - mongo
    volumes:
        - ./:/app
        - /app/node_modules
    build: .
    environment: 
      - PORT=3000
    # ports:
    #   - "3000:3000"
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
  redis:
    image: redis